export default {
  logo: require('@app/assets/images/logo/logo.jpg'),
  logoCircle: require('@app/assets/images/logo/logo_mini.png'),
  icGoogle: require('@app/assets/images/ic_google.png'),
  icClose: require('@app/assets/images/ic_close.png'),
  icHome: require('@app/assets/images/ic_home.png'),
  icBook: require('@app/assets/images/ic_book.png'),
  icRank: require('@app/assets/images/ic_ranking.png'),
  icStorage: require('@app/assets/images/ic_storage_book.png'),
  icUser: require('@app/assets/images/ic_user.png'),
  icSearch: require('@app/assets/images/ic_search.png'),
  icSecure: require('@app/assets/images/ic_secure.png'),
  icArrowRight: require('@app/assets/images/ic_arrow_right.png'),
  icStar: require('@app/assets/images/ic_star.png'),
  icLike: require('@app/assets/images/ic_like.png'),
  icWarning: require('@app/assets/images/ic_warning.png'),
  icView: require('@app/assets/images/ic_view.png'),
  icDefaultImage: require('@app/assets/images/ic_default_image.png'),
  icArrowLeft: require('@app/assets/images/ic_arrow_left.png'),
  icRead: require('@app/assets/images/ic_read.png'),
  icRead: require('@app/assets/images/ic_read.png'),
  icSave: require('@app/assets/images/ic_save_line.png'),
  icSaveFill: require('@app/assets/images/ic_save_fill.png'),
  icHeadPhone: require('@app/assets/images/ic_head_phone.png'),
  icDownLoad: require('@app/assets/images/ic_down_load.png'),
  icArrowDown: require('@app/assets/images/ic_arrow_down.png'),
  icDoubleArrowLeft: require('@app/assets/images/ic_double_arrow_left.png'),
  icDoubleArrow: require('@app/assets/images/ic_double_arrow.png'),
  icList: require('@app/assets/images/ic_list.png'),
  icMenu: require('@app/assets/images/ic_menu.png'),
  icMenuVertical: require('@app/assets/images/ic_menu_vertical.png'),
  icPrev: require('@app/assets/images/ic_prev.png'),
  icNext: require('@app/assets/images/ic_next.png'),
  icFont: require('@app/assets/images/ic_font.png'),
  icFontSize: require('@app/assets/images/ic_font_size.png'),
  icTextColor: require('@app/assets/images/ic_text_color.png'),
  icFillColor: require('@app/assets/images/ic_fill_color.png'),
  icAccount: require('@app/assets/images/ic_account.png'),
  icEmail: require('@app/assets/images/ic_email.png'),
  icDoc: require('@app/assets/images/ic_doc.png'),
  icLogout: require('@app/assets/images/ic_logout.png'),
  icPremium: require('@app/assets/images/ic_premium.png'),
  icSetting: require('@app/assets/images/ic_setting.png'),
  icAdd: require('@app/assets/images/ic_add.png'),
  icSubtract: require('@app/assets/images/ic_subtract.png'),
  icSort: require('@app/assets/images/ic_sort.png'),
  icArrowUp: require('@app/assets/images/ic_arrow_up.png'),
  icDelete: require('@app/assets/images/ic_delete.png'),
  icCancelDelete: require('@app/assets/images/ic_cancel_delete.png'),
  icOpenBook: require('@app/assets/images/ic_open_book.png'),
  //
  icHistory: require('@app/assets/images/ic_history.png'),
  icDropdown: require('@app/assets/images/ic_dropdown.png'),
  icActivate: require('@app/assets/images/ic_activate.png'),
  icMessage: require('@app/assets/images/ic_message.png'),
  //

};
